name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  lambdaDeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main
      - name: list the directories
        run: ls -la
      - name: zip the package
        run: zip -r python.zip hello.py
      - name: check the aws cli
        run: aws --version
      - name: Update Lambda function (direct upload)
        run: aws lambda update-function-code --function-name test-lambda --zip-file fileb://python.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "ap-south-1"
