name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  lambdaDeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main
      - name: list the directories
        run: ls -la
      - name: zip the package
        run: zip -r python.zip hello.zip
      - name: check the aws cli
        run: aws --version
